import { useState } from 'react'
import { useJSON, figURL } from '../lib/data.js'
import { heatColor, fmt } from '../lib/ui.js'
import { METRICS, DIMENSIONS } from '../data/catalog.js'

const LABEL = Object.fromEntries(METRICS.map(m => [m.key, m.label]))

export default function Scorecard() {
  const { data, error } = useJSON('data/scorecard.json')
  const [sortKey, setSortKey] = useState('oracle_agreement')

  if (error) return <Err msg={error} />
  if (!data) return <div className="loading">Loading scorecard…</div>

  const keys = Object.keys(data)
  const rows = [...keys].sort((a, b) => (data[b][sortKey] ?? -1) - (data[a][sortKey] ?? -1))
  const best = {}
  DIMENSIONS.forEach(d => { best[d.key] = keys.reduce((m, k) => (data[k][d.key] > (data[m]?.[d.key] ?? -1) ? k : m), keys[0]) })

  return (
    <div>
      <div className="sec-tag">Bottom line</div>
      <h1 className="sec-title">Metric scorecard</h1>
      <p className="sec-desc">
        Every candidate graded on the PLAN’s evaluation dimensions, each oriented so
        higher = better. Click a column to sort. Cell color is the score (red→green).
        <strong> kNN MME (true) leads on accuracy; voxel-PCA is cheap and scene-stable
        but carries a degeneracy blind spot.</strong>
      </p>

      <div className="card" style={{ overflowX: 'auto', marginBottom: 16 }}>
        <table className="tbl">
          <thead>
            <tr>
              <th>Metric</th>
              {DIMENSIONS.map(d => (
                <th key={d.key} className="num" onClick={() => setSortKey(d.key)}
                    title={d.blurb}>
                  {d.label}{sortKey === d.key ? ' ↓' : ''}
                </th>
              ))}
              <th className="num" onClick={() => setSortKey('compute_ms')}>ms@400k</th>
              <th className="num">scaling</th>
            </tr>
          </thead>
          <tbody>
            {rows.map(k => (
              <tr key={k}>
                <td style={{ fontWeight: 600 }}>{LABEL[k] || k}</td>
                {DIMENSIONS.map(d => (
                  <td key={d.key} className="num">
                    <span className="heat" style={{ background: heatColor(data[k][d.key]) }}>
                      {fmt(data[k][d.key], 2)}{best[d.key] === k ? ' ★' : ''}
                    </span>
                  </td>
                ))}
                <td className="num">{fmt(data[k].compute_ms, 0)}</td>
                <td className="num">N^{fmt(data[k].exponent, 2)}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <div style={{ fontSize: 11, color: 'var(--muted2)', marginTop: 8 }}>★ = best in column.</div>
      </div>

      <div className="grid g2" style={{ marginBottom: 24 }}>
        {DIMENSIONS.map(d => (
          <div className="card card-sm" key={d.key}>
            <div style={{ fontWeight: 700, fontSize: 13 }}>{d.label}</div>
            <div style={{ fontSize: 12.5, color: 'var(--muted)' }}>{d.blurb}</div>
          </div>
        ))}
      </div>

      <div className="label-sm" style={{ marginBottom: 10 }}>Recommendations (PLAN Week 1)</div>
      <div className="card" style={{ marginBottom: 24 }}>
        <ol style={{ margin: '0 0 0 20px', fontSize: 14, lineHeight: 1.8 }}>
          <li><strong>Promote kNN MME (true) to co-primary.</strong> It dominates on accuracy and is the only metric that survives the degeneracy and IMU-grade tests; profile it at real backfill scale before deciding.</li>
          <li><strong>Keep Voxel-PCA, paired with a degeneracy guard.</strong> Cheap, noise-robust, scene-invariant on clean maps — good for the common bias case, but it can’t stand alone. Complement with Qiaojun’s INS metric rather than duplicate coverage.</li>
          <li><strong>Use scene-conditional thresholds</strong> (or condition on a degeneracy indicator) — a single global threshold inherits the blind spot.</li>
          <li><strong>Demote BEV edge density to a cheap pre-filter</strong> — too weak and scene-dependent to be primary.</li>
          <li><strong>Don’t rely on any reference-free crispness metric for dynamic-object contamination</strong> — route that to dynamic removal.</li>
        </ol>
      </div>

      <div className="fig">
        <img src={figURL('f0_scorecard.png')} alt="scorecard heatmap" />
        <div className="fig-cap">F0 · Scorecard heatmap (generated by run_all.py).</div>
      </div>
    </div>
  )
}

const Err = ({ msg }) => (
  <div className="card" style={{ borderColor: 'var(--red)' }}>
    <strong>Couldn’t load data:</strong> {msg}.<br />
    Run <span className="kbd">python experiments/run_all.py</span> then <span className="kbd">npm run sync</span>.
  </div>
)
